//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graph.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graph.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1302526803_refresh {
            get {
                object obj = ResourceManager.GetObject("1302526803_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304843356_repeat {
            get {
                object obj = ResourceManager.GetObject("1304843356_repeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304917464_unlock {
            get {
                object obj = ResourceManager.GetObject("1304917464_unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304922456_sq_plus {
            get {
                object obj = ResourceManager.GetObject("1304922456_sq_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304922462_delete {
            get {
                object obj = ResourceManager.GetObject("1304922462_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304942948_monotone_question {
            get {
                object obj = ResourceManager.GetObject("1304942948_monotone_question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304942974_monotone_arrow_right {
            get {
                object obj = ResourceManager.GetObject("1304942974_monotone_arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304942976_monotone_arrow_play_right_next {
            get {
                object obj = ResourceManager.GetObject("1304942976_monotone_arrow_play_right_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304943027_monotone_document_file_paper {
            get {
                object obj = ResourceManager.GetObject("1304943027_monotone_document_file_paper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304944026_monotone_pen_write {
            get {
                object obj = ResourceManager.GetObject("1304944026_monotone_pen_write", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304944264_monotone_arrow_left_small {
            get {
                object obj = ResourceManager.GetObject("1304944264_monotone_arrow_left_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304944583_monotone_arrow_next_right {
            get {
                object obj = ResourceManager.GetObject("1304944583_monotone_arrow_next_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304944721_monotone_minus_round {
            get {
                object obj = ResourceManager.GetObject("1304944721_monotone_minus_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304945083_playback_reload {
            get {
                object obj = ResourceManager.GetObject("1304945083_playback_reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304949680_monotone_arrow_right_next {
            get {
                object obj = ResourceManager.GetObject("1304949680_monotone_arrow_right_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304949682_monotone_arrow_left {
            get {
                object obj = ResourceManager.GetObject("1304949682_monotone_arrow_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1305795184_exchange {
            get {
                object obj = ResourceManager.GetObject("1305795184_exchange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1306385049_mouse {
            get {
                object obj = ResourceManager.GetObject("1306385049_mouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1306385641_type_list {
            get {
                object obj = ResourceManager.GetObject("1306385641_type-list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1306986276_konqsidebar_mediaplayer {
            get {
                object obj = ResourceManager.GetObject("1306986276_konqsidebar_mediaplayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1306986827_undo {
            get {
                object obj = ResourceManager.GetObject("1306986827_undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1306987935_media_shuffle {
            get {
                object obj = ResourceManager.GetObject("1306987935_media-shuffle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap advanced_silent_update {
            get {
                object obj = ResourceManager.GetObject("advanced_silent_update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gm_canvas_overview {
            get {
                object obj = ResourceManager.GetObject("gm_canvas_overview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Nsoft {
            get {
                object obj = ResourceManager.GetObject("Nsoft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap popup_background {
            get {
                object obj = ResourceManager.GetObject("popup_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap popup_informative {
            get {
                object obj = ResourceManager.GetObject("popup_informative", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap progress_fgr_black {
            get {
                object obj = ResourceManager.GetObject("progress_fgr_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
